export const ERROR_CODES = {
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
    DOCUMENT_FORBIDDEN: "DOCUMENT_FORBIDDEN",
    DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
