export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
  DOCUMENT_FORBIDDEN: "DOCUMENT_FORBIDDEN",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_SHARE_FORBIDDEN: "DOCUMENT_SHARE_FORBIDDEN",
  DOCUMENT_READ_ONLY: "DOCUMENT_READ_ONLY",
  BLOCK_NOT_FOUND: "BLOCK_NOT_FOUND",
  BLOCK_FORBIDDEN: "BLOCK_FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
